on: workflow_dispatch

name: test

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - run: Rscript -e 'install.packages("testthat")'
      - run: Rscript -e 'testthat::test_dir("tests/", stop_on_failure = T)'
